### PR TITLE
fix bug by adding check-and-set option to write in vault when needed

### LINKED ISSUE #29: Potential race condition when reading then writing in Vault KV
In different part of our API where we need to update a key/value, we read information from Vault KV and then write the updated version of the key.
For example when we associate a secret to a group:
Read the group secret list:
https://github.com/Orange-OpenSource/remote-key-server/blob/0fb10171dd824b20ac5b892cd083ceddd99d7508/pkg/api/admin/administration.go#L412

Write the group secret list:
https://github.com/Orange-OpenSource/remote-key-server/blob/0fb10171dd824b20ac5b892cd083ceddd99d7508/pkg/api/admin/administration.go#L428

A problem happens if we have concurrent requests and the key value changes before the update value is written. For example here, if the group secret list is updated after the Read but before the Write, once the write happens the update will be erased.

This can be fixed by using Vault Check And Set (cas) feature: https://www.vaultproject.io/api-docs/secret/kv/kv-v2#cas

On key write/update you also specify last known key version (obtained in the metadata of the key read before or 0 if the key doesn't exist), Vault will only apply the write/update if the key version is the one specified.

So if an update happened in between the Read and Write version will differ and the write won't be allowed.

Since Write can fail with CAS this will need a retry mechanism where if failed we read the key again and retry to update it.

### PR DESCRIPTION
**Pull request by celinenicolas22**
Signed-off-by: Céline Nicolas <celine.nicolas@orange.com>

### CODE REVIEW

**Comment by gfeun** [comment]
I added the locust test file to check if the race is still present.

To launch the test you can use: 
```bash
./scripts/generate_test_certificates.sh
# Ctrl-C when you have enough (100 is good)
make dev-env -j4 > /dev/null && tox -c ./tests/tox.ini -e locust -- --headless -H https://localhost:8080 -u 30 -r 30 -t 5s --only-summary
```

File: pkg/api/admin/administration.go [hunk 1]
```diff
@@ -402,25 +402,31 @@ func AssociateSecret(w http.ResponseWriter, r *http.Request) {
...
-	if rksErr != nil {
-		rksErr.HandleErr(r.Context(), w)
-		return
-	}
+	var groupSecrets *model.GroupSecrets
 
-	for _, secret := range groupSecrets.Secrets {
-		if secret == fqdn {
-			(&model.RksError{WrappedError: nil, Message: fqdn + "already associated to " + group, Code: 409}).HandleErr(r.Context(), w)
+	for {
```
Comment (gfeun) [inline pkg/api/admin/administration.go]: As discussed yesterday, I'd put a max retry number in the for loop to avoid infinite loop in case Vault becomes unavailable. I'm not sure about the number of retry to allow. We should test different values with the locust test case

something like this:
```go
i := 0
for {
  // ...
  if i > 3 {
  // RksError 500
  }
  i++
}

File: pkg/api/admin/administration.go [hunk 2]
```diff
@@ -466,28 +472,29 @@ func DissociateSecret(w http.ResponseWriter, r *http.Request) {
...
-		rksErr.HandleErr(r.Context(), w)
-		return
-	}
-
-	found := false
-	for _, secret := range groupSecrets.Secrets {
-		if secret == fqdn {
-			found = true
+	var groupSecrets *model.GroupSecrets
+	for {
```
Comment (gfeun) [inline pkg/api/admin/administration.go]: Same as for the associate secret infinite for loop above

File: pkg/vault/client.go [hunk 3]
```diff
@@ -37,12 +38,13 @@ type Configuration struct {
...
 }
 
-// Config is the global config struct
+// Configs the global config struct
 var Config Configuration
 
 type Vault struct {
 	*vaultAPI.Client
 	logger logrus.FieldLogger
+	//	casOpt int
```
Comment (gfeun) [inline pkg/vault/client.go]:
```suggestion
```

**Review by gfeun — CHANGES_REQUESTED** [review]
